import type { Metadata } from "next";
import { Commissioner } from "next/font/google";
import Avatar from "@/assets/images/yoyoyo.jpg";
import "./globals.css";
import Link from "next/link";

const commissioner = Commissioner({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={commissioner.className}>
				<main className="grid min-h-screen items-center py-20 bg-gray-900">
					<div className="mx-auto rounded-md bg-gradient-to-r from-pink-500 via-red-500 to-yellow-500 p-1 sm:w-[500px] md:w-[700px]">
						<div className="rouded bg-gray-100 p-8">
							<Link href="/">
								<img
									src={Avatar.src}
									alt="Imagen avatar de presentacion"
									className="mx-auto -mt-20 mb-8 rounded-full"
									width={100}
									height={100}
								/>
							</Link>
							{children}
						</div>
					</div>
				</main>
			</body>
		</html>
	);
}
