import ButtonLink from "@/components/ButtonLink";
import React from "react";

export const metadata = {
	title: "Home page / Create next-app",
	description: "Generated by create next app",
};

const Home = () => {
	return (
		<>
			<h1 className="text-center text-3xl font-bold uppercase">
				Juan Pedro
			</h1>
			<p className="mb-8 text-center text-gray-700">Front End Developer</p>
			<p className="mb-8 text-center">
				Lorem ipsum dolor, sit amet consectetur adipisicing elit. Nemo quia
				ratione qui dignissimos, a debitis cupiditate ducimus explicabo
				necessitatibus quam quidem et incidunt, commodi sit magnam? Magnam
				quae recusandae incidunt.
			</p>
			<div className="text-center">
				<ButtonLink href="/blog">Ir al blog</ButtonLink>
			</div>
		</>
	);
};

export default Home;
